// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmPSfF2UioM72pmjjlq3l7f7zyJnZhqX8',
    appId: '1:226159835476:android:50464788a9ff3646fe30c1',
    messagingSenderId: '226159835476',
    projectId: 'instagram-clon-2b8bd',
    storageBucket: 'instagram-clon-2b8bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcFl9kxlWtTsE81S2HZsru9Is7ZsOpB6M',
    appId: '1:226159835476:ios:cbc847dd935306aefe30c1',
    messagingSenderId: '226159835476',
    projectId: 'instagram-clon-2b8bd',
    storageBucket: 'instagram-clon-2b8bd.appspot.com',
    androidClientId: '226159835476-e9ecklp1dilv5ur1nn0sm02e2a48csst.apps.googleusercontent.com',
    iosClientId: '226159835476-sjckabk73aodtb90ifnsenn6shoeielh.apps.googleusercontent.com',
    iosBundleId: 'zepetto.com.instagramClon',
  );
}
