spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none #자동 테이블 생성
    properties:
      hibernate:
        #        show_sql: true #system.out에서 찍는 로그
        format_sql: true